all:
	@$(MAKE) --no-print-directory -C test_Arduino_implementation/
	@$(MAKE) --no-print-directory -C test_ESP_IDF_implementation/

clean:
	@$(MAKE) clean --no-print-directory -C test_Arduino_implementation/
	@$(MAKE) clean --no-print-directory -C test_ESP_IDF_implementation/